[댓글과 로그인] 과제 리뷰 요청합니다.
code-squad/masteringjs_async pull request #5
Opened 2018-10-12 16:05 UTC by hyeyoon

안녕하세요 크롱님!
댓글과 로그인 과제 제출합니다 리뷰 부탁드립니다 :)

2018-10-15 05:15 UTC, crongro requested changes
깔끔한 코드네요.

리뷰남겨드리는 것 참고하세요~

수고하셨어요.

2018-10-15 05:15 UTC, nigayo commented on public/qna.js
> +    .then(() => loggingData('Delete answer'))
먼저 logging하는 과정이 옵션이면 if문으로 추가하는 것도 필요할 듯.

그리고,
loggingData 처럼 함수로 위임해도 되고요.
여기서 thenable하게 쭉 표현하는 것도 전 좋을거 같고요.

2018-10-15 05:15 UTC, nigayo commented on public/qna.js
> +  fetch('/api/logging', {
logging은 fetchManager를 못쓰는 상황인가보네요.
가급적 일관된 방식으로 사용하는 것이 낫습니다.

2018-10-15 05:15 UTC, nigayo commented on public/qna.js
> +    const callbackReturn = await callback(checkedResponse);
await잘쓰셨어요.

2018-10-15 05:15 UTC, nigayo commented on public/qna.js
> +    console.error(error);
잘 아시겠지만, catch 상황으로 에러가 잘 넘어오고, 에러처리가 잘 되는지는 항상 잘 테스트하시는 게 좋아요~

2018-10-15 05:15 UTC, nigayo commented on public/qna.js
> +  for (let i = 0; i < answers.children.length; i++) {
nodeList도 for-of를 쓸 수 있고, forEach도 쓸 수 있으니, 
두 가지 방법이 for보다 낫죠.

2018-10-15 05:15 UTC, nigayo commented on public/qna.js
> +function delegateEventToChild(event) {
delegate 상황을 분리한 건 좋네요~

2018-10-15 05:15 UTC, nigayo commented on public/qna.js
> +  if (event.target.tagName === 'A') {
A가 아니면 바로 return 하는게 indent를 줄이는 거겠죠.

2018-10-19 10:44 UTC, hyeyoon commented
코드리뷰를 바탕으로 리팩토링을 해봤습니다 :)

2018-10-21 11:10 UTC, crongro approved these changes
아고 끝까지 잘 수정하셨네요.
💯

2018-10-21 11:10 UTC, merged